---

- name: Restart sensu-server
  service:
    name: sensu-server
    state: restarted

- name: Restart sensu-api
  service:
    name: sensu-api
    state: restarted

- name: Restart sensu-client
  service:
    name: sensu-client
    state: restarted
